from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login, name="login"),
    path('login', views.login, name="login"),
    path('signup', views.signup, name='signup'),
    path('signupvol', views.signupvol, name='signupvol'),
    path('admin_home', views.admin_home, name='admin_home'),
    path('admin_pending_volunteers', views.admin_pending_volunteers, name='admin_pending_volunteers'),
    path('admin_approved_volunteers', views.admin_approved_volunteers, name='admin_approved_volunteers'),
    path('admin_view_vol_post/<str:id>', views.admin_view_vol_post, name='admin_view_vol_post'),
    path('admin_approve_volunteers/<str:id>',views.admin_approve_volunteers, name='admin_approve_volunteers'),
    path('vol_home', views.vol_home, name='vol_home'),
    path('add_post', views.add_post, name='add_post'),
    path('make_post', views.make_post, name='make_post'),
    path('vol_posts', views.vol_posts, name='vol_posts'),
    path('user_home', views.user_home, name='user_home'),
    path('view_posts', views.view_posts, name='view_posts'),
    path('abort_post/<str:id>', views.abort_post, name='abort_post'),
    path('activate_post/<str:id>', views.activate_post, name='activate_post'),
    path('send_donation_request/<int:id>', views.send_donation_request, name='send_donation_request'),
    path('send_donation_response', views.send_donation_response, name='send_donation_response'),
    path('approved_donation_requests', views.approved_donation_requests, name='approved_donation_requests'),
    path('payed_donation_requests', views.payed_donation_requests, name='payed_donation_requests'),
    path('vol_payed_donation_requests/<str:id>', views.vol_payed_donation_requests, name='vol_payed_donation_requests'),
    path('admin_vol_payed_donation_requests/<str:id>', views.admin_vol_payed_donation_requests, name='admin_vol_payed_donation_requests'),
    path('pending_donation_requests/<int:id>', views.pending_donation_requests, name='pending_donation_requests'),
    path('accept_donation_response/<str:id>', views.accept_donation_response, name='accept_donation_response'),
    path('accepted_donation_requests/<int:id>', views.accepted_donation_requests, name='accepted_donation_requests'),
    path('vol_view_user_donation/<str:jd>/<str:kd>', views.vol_view_user_donation, name='vol_view_user_donation'),
    path('user_view_donation/<str:id>/<str:jd>', views.user_view_donation, name='user_view_donation'),
    path('make_payment/<str:id>/<str:res>', views.make_payment, name='make_payment'),
    path('donate_items/<str:id>/<str:res>', views.donate_items, name='donate_items'),
    path('validate_payment', views.validate_payment, name='validate_payment'),
    path('requested_item_requests/<str:id>', views.requested_item_requests, name='requested_item_requests'),
    path('accept_donation_items/<str:id>', views.accept_donation_items, name='accept_donation_items'),
    path('accepted_item_requests/<int:id>', views.accepted_item_requests, name='accepted_item_requests'),
    path('admin_accepted_item_requests/<int:id>', views.admin_accepted_item_requests, name='admin_accepted_item_requests'),
    path('collected_item_requests/<int:id>', views.collected_item_requests, name='collected_item_requests'),
    path('user_accepted_item_requests',views.user_accepted_item_requests, name='user_accepted_item_requests'),
    path('cancel_donation_item/<str:id>', views.cancel_donation_item, name='cancel_donation_item'),
    path('admin_view_vol_post/<str:id>', views.admin_view_vol_post, name='admin_view_vol_post'),
    path('user_send_feedback/<str:id>', views.user_send_feedback, name='user_send_feedback'),
    path('send_feedback/<str:id>', views.send_feedback, name='send_feedback'),
    path('user_view_feedback/<str:id>', views.user_view_feedback, name='user_view_feedback'),
    path('vol_view_feedback/<str:id>', views.vol_view_feedback, name='vol_view_feedback'),
    path('add_money_spend', views.add_money_spend, name='add_money_spend'),
    path('upload_money_spend', views.upload_money_spend, name='upload_money_spend'),
    path('vol_money_spends', views.vol_money_spends, name='vol_money_spends'),
    path('admin_view_money_spend/<str:id>', views.admin_view_money_spend, name='admin_view_money_spend'),
    path('admin_view_feedback/<str:id>', views.admin_view_feedback, name='admin_view_feedback'),
]